language: python

sudo: false

branches:
  except:
    - yellowstone-env
    - yellowstone-convert-to-esmf

env:
  - CONDA_PYTHON="python=2.7"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --all --yes
  - conda info -a

install:
  - conda create -n test-with-ocgis -y -c nesii/channel/dev-esmf -c nesii esmpy==HEAD ocgis nose
  - source activate test-with-ocgis
  - conda remove -y ocgis
  - pip install logbook
  - git clone -b pmesh-ugrid-nfie https://github.com/NCPP/ocgis.git && cd ocgis && python setup.py install
  - cd ..

  - conda create -n test-without-ocgis-rtree -y -c nesii/channel/dev-esmf -c nesii esmpy==HEAD ocgis nose
  - source activate test-without-ocgis-rtree
  - conda remove -y ocgis rtree
  - pip install logbook

script:
  - source activate test-with-ocgis
  - bash test.sh
  - python setup.py install
  - python -c "import utools"
  - utools_cli --help

  - source activate test-without-ocgis-rtree
  - bash test.sh
  - python setup.py install
  - python -c "import utools"
  - utools_cli --help
